//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ReservationID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
